name: Container
on: push

jobs:
  node-docker:
      runs-on: ubuntu-latest
      container: 
        image: nginx:latest
      steps:
        - name: Log node version
          run: |
            nginx -v
            cat /etc/os-release
        
        - name: FS details
          run: |
            df -h
            hostname

