name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: nginx:latest
    steps:
      - name: Log node version
        run: | 
          node -v
          cat /etc/os-release
      
      - name: File syste Details
        run: |
          df -hPT
          hostname
          uname -r
