name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: rajkumar25maurya/docker-nodejs-api_app:v1  ## This docker image is on docker hub
        ports:
          - "3001:3000"
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: List the container
        run: docker ps
      - name: Post a User   # it post the user
        run: 'curl -X POST  http://localhost:3001/api/user -H ''Content-Type: application/json'' -d  ''{"username": "hello","address": "pune"}'''
      
      - name: Get Users
        run: curl http://localhost:3001/api/users