name: matrix
on: push

jobs:
  node-version:
    runs-on: ubuntu-latest
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 9
      - name: Log nopde version
        run: node -v
        
