name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    needs: ['run-windows-commands']
    steps:
      - name: echo a string
        run: echo "Hello World"
      
      - name: echo multiline script
        run: |    # It will allow to run multiline command
          node -v
          npm -v
          uname -r
      
      - name: python commands
        run: |
          import platform
          print (platform.processor())
        shell: python   # this command will run in python shell
  
  run-windows-commands:
    runs-on: windows-latest
    #needs: ['run-shell-command'] # this is depend on shell-command job, this job will run when shell-command job ran successfully
    steps:
      - name: Directory Pwershell
        run:  Get-Location
      
      - name: Directory Bash
        run: pwd
        shell: bash
        