name: Shell command

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      
      - name: echo Multiline script
        run: | # it will allow to run multiline command
          node -v
          npm -v
          uname -r
          uptime
          df -hT
          echo $PATH
      
      - name: python commands
        run: |
          import platform
          print(platform.proceor())
        shell: ptyhon
 
